import Providers from "@/app/providers"
import type { Metadata } from "next"
import "./globals.css"
import { ReactNode } from "react"

type Props = {
  children: ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
const RootLayout = (props: Props) => {
  const { children } = props

  return (
    <Providers>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Providers>
  )
}

export default RootLayout
