import type { Metadata } from "next"
import { ReactNode } from "react"
import { Toaster } from "sonner"

import Footer from "@/components/Footer"
import Header from "@/components/Header"
import SearchContainer from "@/components/SearchContainer"
import type { PageProps } from "@/types/common"

import "./globals.css"
import Providers from "./providers"

type Props = {
  children: ReactNode
} & PageProps

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
const RootLayout = (props: Props) => {
  const {
    children,
    params: { locale },
  } = props

  return (
    <Providers>
      <html lang={locale} className="bg-background">
        <body className="flex flex-col justify-between w-full min-h-screen min-w-80">
          <Toaster
            closeButton
            position="bottom-right"
            toastOptions={{
              classNames: {
                default:
                  "rounded-default border border-border bg-card shadow-lg",
                closeButton: "bg-card",
                error: "text-danger",
                success: "text-success",
              },
            }}
          />
          <Header />
          <main className="grow">{children}</main>
          <Footer />
          <SearchContainer />
        </body>
      </html>
    </Providers>
  )
}

export default RootLayout
