import type { Metadata } from "next"
import { ReactNode } from "react"

import type { Locale } from "@airneis/types/Locale"

import "./globals.css"
import Providers from "./providers"

type Props = {
  children: ReactNode
  params: {
    locale: Locale
  }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
const RootLayout = (props: Props) => {
  const {
    children,
    params: { locale },
  } = props

  return (
    <Providers>
      <html lang={locale}>
        <body>{children}</body>
      </html>
    </Providers>
  )
}

export default RootLayout
